[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
board_build.partitions = huge_app.csv
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    powerbroker2/ELMduino@^3.1.2
    lvgl/lvgl@^8.3.11

build_flags =
    -D LV_CONF_SKIP=1
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=0
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_18=1
    -D LV_FONT_MONTSERRAT_24=1
    -D LV_FONT_MONTSERRAT_48=1
